language: python
python:
  - "2.7"

install:
  - pip install -r requirements-tests.txt  

before_script:
  - cp .env.example .env

script:
 - python manage.py  test --settings=eletronica.settings.development
